FROM ubuntu:16.04
MAINTAINER Lei Pan

LABEL version="1.0"
LABEL description="Image to execute user code"

RUN apt-get update
RUN apt-get install -y openjdk-8-jdk
RUN apt-get install -y python3
RUN apt-get install -y g++
